# Generated by Django 3.1.1 on 2020-09-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0002_auto_20200930_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='img',
            field=models.ImageField(upload_to='media1'),
        ),
    ]
