# Generated by Django 3.1.1 on 2020-09-30 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pred', '0003_auto_20200930_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='area',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='perimeter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='radius',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='smoothness',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='report',
            name='texture',
            field=models.CharField(max_length=100),
        ),
    ]
